# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce53291a5455b5f90874d6600811e3924fbec5011fa4993227cb8ad901397a32a4052d0e7f62fe0117bd76f7164b6ae3f24a7d4df788831fc521eb5fd65d5353

test:
  secret_key_base: eab45531423211cfd98f2dbeb68afa4df6a97c898f79d2ed3780c4c2506e5e7a8669a5a8aee8803f982c996145b6ae5b0d332da7bc2d1036577edd5bd3c97562

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
